name = "BnGStructs"
uuid = "764f5799-4fa8-443f-b488-b719b6ff37e3"
version = "0.2.3"
authors = ["Xijiang Yu <xijiang@users.noreply.github.com>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Distributions = "0.25"
Random = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
